###
POST http://localhost:8081/api/v1/operator/sessions/authorize
Content-Type: application/json

{
  "login": "ivanov",
  "password": "password123",
  "workplace": "WP005"
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/open
Content-Type: application/json

{
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/request-client
Content-Type: application/json

{
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/assign-client
Content-Type: application/json

{
  "ticketNumber": "T01"
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/start-client-session
Content-Type: application/json

{
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/complete-client-session
Content-Type: application/json

{
}

###
POST http://localhost:8081/api/v1/operator/sessions/01990d32-8daf-7bba-8654-6adeccf02e30/close
Content-Type: application/json

{
}

