services:
  postgres:
    image: postgres:17.5
    container_name: operator_interface_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    command: [ "postgres", "-c", "log_statement=mod" ]

  operator-authorization:
    image: operator-authorization-service
    build:
      context: .
      dockerfile: src/MockOperatorAuthorizationService/Dockerfile
    ports:
      - "5001:5001"
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ASPNETCORE_URLS": "https://+;http://+"
      "ASPNETCORE_Kestrel__Certificates__Default__Password": "P@ssw0rd1"
      "ASPNETCORE_Kestrel__Certificates__Default__Path": "/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro

  operator-api:
    image: operator-api-image
    build:
      context: .
      dockerfile: src/OperatorInterface.Api/Dockerfile
    environment:
      "ASPNETCORE_URLS": "http://+:8080"
      "CONNECTION_STRING": "Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=operator_interface;"
      "AUTH_SERVICE_GRPC_HOST": "http://operator-authorization:5001"
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - operator-authorization
        
  operator-app:
    image: operator-app-image
    build:
      context: .
      dockerfile: src/OperatorInterface.BlazorApp/Dockerfile
    environment:
      "ASPNETCORE_URLS": "http://+:8080"
      "CONNECTION_STRING": "Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=operator_interface;"
      "AUTH_SERVICE_GRPC_HOST": "http://operator-authorization:5001"
    ports:
      - "8083:8080"
    depends_on:
      - postgres
      - operator-authorization



